version: "3.8"

services:
  llm_service:
    build: ./LLM_service
    ports:
      - "8000:8000"
    volumes:
      # монтируем папку с моделью внутрь контейнера
      - ./LLM_service/models:/app/models
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/cluster"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped